name: lint-build-push-deploy
on:
  push:
    tags:
      - "*"
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          verbose: true

      - uses: psf/black@258e7dbf348bc23cb70b8cdf693481c04634ebcc # stable
        with:
          options: "--check --verbose"

  build-push:
    needs: [lint]
    uses: lehigh-university-libraries/gha/.github/workflows/build-push-ghcr.yaml@e26d86abfbe300be4d93570b666651c11471995b # main
    permissions:
      contents: read
      packages: write
    secrets: inherit

  deploy:
    needs: [build-push]
    uses: lehigh-university-libraries/gha/.github/workflows/linderman-deploy.yaml@e26d86abfbe300be4d93570b666651c11471995b # main
    with:
      url: https://apps-test.lib.lehigh.edu/_rollout
    secrets: inherit
    permissions:
      contents: read
      id-token: write
